name: example_patrol_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  patrol: ^1.0.8

patrol:
  app_name: flavor1 example
  flavor: flavor1
  android:
    package_name: com.example.example_patrol_app.flavor1
  ios:
    bundle_id: com.example.example_patrol_app.flavor1

flutter:
  uses-material-design: true
